name: Neural Inspect
description: Action to trigger an automated, AI powered, code review
author: Neural Inspect

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github_token:
    description: The token used to connect to GitHub
    required: true
  api_key:
    description: Your Neural Inspect API key
    required: true

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
